var _capsule_collider_particle_synchronizer_8cs =
[
    [ "Bones.Gameplay.Effects.Containers.Projectiles.CapsuleColliderParticleSynchronizer", "class_bones_1_1_gameplay_1_1_effects_1_1_containers_1_1_projectiles_1_1_capsule_collider_particle_synchronizer.html", "class_bones_1_1_gameplay_1_1_effects_1_1_containers_1_1_projectiles_1_1_capsule_collider_particle_synchronizer" ]
];