var _float_subtracting_transitive_effect_8cs =
[
    [ "Bones.Gameplay.Effects.Transitive.Depth.FloatSubtractingTransitiveEffect", "class_bones_1_1_gameplay_1_1_effects_1_1_transitive_1_1_depth_1_1_float_subtracting_transitive_effect.html", "class_bones_1_1_gameplay_1_1_effects_1_1_transitive_1_1_depth_1_1_float_subtracting_transitive_effect" ]
];