var _stat_to_variable_transitive_effect_8cs =
[
    [ "Bones.Gameplay.Effects.Transitive.Depth.StatToVariableTransitiveEffect", "class_bones_1_1_gameplay_1_1_effects_1_1_transitive_1_1_depth_1_1_stat_to_variable_transitive_effect.html", "class_bones_1_1_gameplay_1_1_effects_1_1_transitive_1_1_depth_1_1_stat_to_variable_transitive_effect" ]
];